// ===== EXERCISE DATABASE =====
export const EXERCISE_DB = [
  { name:'Hip Thrust', cat:'Glutes', muscles:['gluteal','hamstring'] },
  { name:'Romanian Deadlift', cat:'Glutes', muscles:['hamstring','gluteal','lower-back'] },
  { name:'Barbell Romanian Deadlift', cat:'Glutes', muscles:['hamstring','gluteal','lower-back'] },
  { name:'Dumbbell Romanian Deadlift', cat:'Glutes', muscles:['hamstring','gluteal','lower-back'] },
  { name:'Cable Kickback', cat:'Glutes', muscles:['gluteal'] },
  { name:'Machine Standing Hip Abduction', cat:'Glutes', muscles:['abductors','gluteal'] },
  { name:'Machine Seated Hip Abduction', cat:'Glutes', muscles:['abductors','gluteal'] },
  { name:'Single Leg Cable Kickback', cat:'Glutes', muscles:['gluteal','hamstring'] },
  { name:'Sumo Squat', cat:'Glutes', muscles:['gluteal','quadriceps','adductors'] },
  { name:'Hip Abduction Machine', cat:'Glutes', muscles:['abductors','gluteal'] },
  { name:'Glute Bridge', cat:'Glutes', muscles:['gluteal','hamstring'] },
  { name:'Donkey Kick', cat:'Glutes', muscles:['gluteal'] },
  { name:'Squat', cat:'Legs', muscles:['quadriceps','gluteal','hamstring'] },
  { name:'Barbell Squat', cat:'Legs', muscles:['quadriceps','gluteal','hamstring'] },
  { name:'Dumbbell Squat', cat:'Legs', muscles:['quadriceps','gluteal','hamstring'] },
  { name:'Leg Press', cat:'Legs', muscles:['quadriceps','gluteal','hamstring'] },
  { name:'Leg Extension', cat:'Legs', muscles:['quadriceps'] },
  { name:'Leg Curl', cat:'Legs', muscles:['hamstring'] },
  { name:'Walking Lunge', cat:'Legs', muscles:['quadriceps','gluteal','hamstring'] },
  { name:'Reverse Lunge', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Bulgarian Split Squat', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Barbell Bulgarian Split Squat', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Dumbbell Bulgarian Split Squat', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Hack Squat', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Goblet Squat', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Calf Raise', cat:'Legs', muscles:['calves'] },
  { name:'Seated Calf Raise', cat:'Legs', muscles:['calves'] },
  { name:'Lying Leg Curl', cat:'Legs', muscles:['hamstring'] },
  { name:'Standing Leg Curl', cat:'Legs', muscles:['hamstring'] },
  { name:'Adductor Machine', cat:'Legs', muscles:['adductors'] },
  { name:'Step Up', cat:'Legs', muscles:['quadriceps','gluteal'] },
  { name:'Lat Pulldown', cat:'Back', muscles:['lats','biceps'] },
  { name:'Seated Cable Row', cat:'Back', muscles:['lats','rhomboids','biceps'] },
  { name:'Bent Over Row', cat:'Back', muscles:['lats','rhomboids','rear-deltoids'] },
  { name:'T-Bar Row', cat:'Back', muscles:['lats','rhomboids'] },
  { name:'Deadlift', cat:'Back', muscles:['lower-back','gluteal','hamstring','traps'] },
  { name:'Pull Up', cat:'Back', muscles:['lats','biceps'] },
  { name:'Chin Up', cat:'Back', muscles:['lats','biceps'] },
  { name:'Cable Straight Arm Pulldown', cat:'Back', muscles:['lats'] },
  { name:'Single Arm Dumbbell Row', cat:'Back', muscles:['lats','rhomboids'] },
  { name:'Smith Machine Row', cat:'Back', muscles:['lats','rhomboids'] },
  { name:'Face Pull', cat:'Back', muscles:['rear-deltoids','traps'] },
  { name:'Hyperextension', cat:'Back', muscles:['lower-back','gluteal'] },
  { name:'Good Morning', cat:'Back', muscles:['lower-back','hamstring'] },
  { name:'Barbell Row', cat:'Back', muscles:['lats','rhomboids','biceps'] },
  { name:'Barbell Bench Press', cat:'Chest', muscles:['chest','triceps','front-deltoids'] },
  { name:'Dumbbell Bench Press', cat:'Chest', muscles:['chest','triceps','front-deltoids'] },
  { name:'Incline Bench Press', cat:'Chest', muscles:['chest','front-deltoids','triceps'] },
  { name:'Decline Bench Press', cat:'Chest', muscles:['chest','triceps'] },
  { name:'Machine Chest Press', cat:'Chest', muscles:['chest','triceps'] },
  { name:'Cable Fly', cat:'Chest', muscles:['chest'] },
  { name:'Pec Deck Fly', cat:'Chest', muscles:['chest'] },
  { name:'Dumbbell Fly', cat:'Chest', muscles:['chest'] },
  { name:'Push Up', cat:'Chest', muscles:['chest','triceps','front-deltoids'] },
  { name:'Dip', cat:'Chest', muscles:['chest','triceps'] },
  { name:'Overhead Press', cat:'Shoulders', muscles:['front-deltoids','side-deltoids','triceps'] },
  { name:'Dumbbell Shoulder Press', cat:'Shoulders', muscles:['front-deltoids','side-deltoids','triceps'] },
  { name:'Lateral Raise', cat:'Shoulders', muscles:['side-deltoids'] },
  { name:'Dumbbell Seated Lateral Raise', cat:'Shoulders', muscles:['side-deltoids'] },
  { name:'Front Raise', cat:'Shoulders', muscles:['front-deltoids'] },
  { name:'Rear Delt Fly', cat:'Shoulders', muscles:['rear-deltoids'] },
  { name:'Arnold Press', cat:'Shoulders', muscles:['front-deltoids','side-deltoids','rear-deltoids'] },
  { name:'Upright Row', cat:'Shoulders', muscles:['side-deltoids','traps'] },
  { name:'Cable Lateral Raise', cat:'Shoulders', muscles:['side-deltoids'] },
  { name:'Machine Shoulder Press', cat:'Shoulders', muscles:['front-deltoids','side-deltoids'] },
  { name:'Barbell Curl', cat:'Arms', muscles:['biceps'] },
  { name:'Dumbbell Curl', cat:'Arms', muscles:['biceps'] },
  { name:'Hammer Curl', cat:'Arms', muscles:['biceps'] },
  { name:'Preacher Curl', cat:'Arms', muscles:['biceps'] },
  { name:'Cable Curl', cat:'Arms', muscles:['biceps'] },
  { name:'Concentration Curl', cat:'Arms', muscles:['biceps'] },
  { name:'Tricep Pushdown', cat:'Arms', muscles:['triceps'] },
  { name:'Skull Crusher', cat:'Arms', muscles:['triceps'] },
  { name:'Overhead Tricep Extension', cat:'Arms', muscles:['triceps'] },
  { name:'Cable Tricep Kickback', cat:'Arms', muscles:['triceps'] },
  { name:'Close Grip Bench Press', cat:'Arms', muscles:['triceps','chest'] },
  { name:'Wrist Curl', cat:'Arms', muscles:['forearm'] },
  { name:'Plank', cat:'Core', muscles:['abs'] },
  { name:'Crunch', cat:'Core', muscles:['abs'] },
  { name:'Cable Crunch', cat:'Core', muscles:['abs'] },
  { name:'Leg Raise', cat:'Core', muscles:['abs'] },
  { name:'Russian Twist', cat:'Core', muscles:['abs','obliques'] },
  { name:'Side Plank', cat:'Core', muscles:['obliques'] },
  { name:'Ab Rollout', cat:'Core', muscles:['abs'] },
  { name:'Hanging Leg Raise', cat:'Core', muscles:['abs'] },
  { name:'Mountain Climber', cat:'Core', muscles:['abs'] },
  { name:'Dead Bug', cat:'Core', muscles:['abs'] },
  { name:'Power Clean', cat:'Full Body', muscles:['quadriceps','gluteal','hamstring','traps','lower-back'] },
  { name:'Kettlebell Swing', cat:'Full Body', muscles:['gluteal','hamstring','lower-back'] },
  { name:'Burpee', cat:'Full Body', muscles:['chest','quadriceps','abs'] },
  { name:'Treadmill', cat:'Cardio', muscles:['quadriceps','calves','hamstring'] },
  { name:'Elliptical', cat:'Cardio', muscles:['quadriceps','hamstring','calves'] },
  { name:'Rowing Machine', cat:'Cardio', muscles:['lats','rhomboids','biceps','quadriceps'] },
  { name:'Stair Climber', cat:'Cardio', muscles:['gluteal','quadriceps','calves'] },
  { name:'Stepper', cat:'Cardio', muscles:['gluteal','quadriceps','calves'] },
  { name:'Battle Ropes', cat:'Cardio', muscles:['front-deltoids','side-deltoids','abs'] },
];

export const CATS = ['All', ...new Set(EXERCISE_DB.map(e => e.cat))];
